const launch=document.getElementById('launch-game'),choices=[...document.querySelectorAll('input[name=edition]')];
let choice='modern';try{const saved=localStorage.getItem('arkanoid-edition');if(saved==='classic')choice='classic';}catch{}
function select(value){choice=value;for(const input of choices)input.checked=input.value===value;launch.href=value==='classic'?'classic.html':'modern.html?play=1';launch.querySelector('span').textContent=value==='classic'?'ИГРАТЬ В CLASSIC':'ИГРАТЬ В NEON HORIZON';try{localStorage.setItem('arkanoid-edition',value);}catch{}}
for(const input of choices)input.addEventListener('change',()=>select(input.value));select(choice);
document.addEventListener('keydown',e=>{if(e.code==='Enter'&&!['A','BUTTON'].includes(e.target.tagName)){e.preventDefault();launch.click();}});
const previews=[{canvas:document.getElementById('classic-preview'),modern:false},{canvas:document.getElementById('modern-preview'),modern:true}],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){for(const p of previews){const rect=p.canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,3);p.canvas.width=Math.max(1,Math.round(rect.width*dpr));p.canvas.height=Math.max(1,Math.round(rect.height*dpr));p.ctx=p.canvas.getContext('2d');}if(reduced)requestAnimationFrame(frame);}
new ResizeObserver(resize).observe(document.querySelector('.edition-picker'));resize();
function frame(now){for(const p of previews){const c=p.ctx,w=p.canvas.width,h=p.canvas.height,s=w/400,t=reduced?0:now/1000;c.clearRect(0,0,w,h);c.save();c.scale(s,s);const hh=h/s;const colors=p.modern?['#987fe6','#809ef5','#55d9d0','#78ddb3']:['#e96469','#e6b94a','#61ba75','#569ddd'];for(let row=0;row<4;row++)for(let col=0;col<10;col++){if(p.modern&&((row===3&&(col<2||col>7))||(row===0&&(col<1||col>8))))continue;const x=36+col*33,y=43+row*16;c.fillStyle=colors[row];if(p.modern){c.shadowColor=colors[row];c.shadowBlur=8;c.fillStyle=colors[row]+'50';c.beginPath();c.roundRect(x,y,29,11,2);c.fill();c.shadowBlur=0;c.strokeStyle=colors[row]+'c0';c.stroke();c.fillStyle=colors[row];c.fillRect(x+2,y+1,25,1);}else{c.fillRect(x,y,31,12);c.fillStyle='#ffffff55';c.fillRect(x,y,31,2);c.fillStyle='#0004';c.fillRect(x,y+10,31,2);}}
const x=200+Math.sin(t*.8)*65,py=hh-22,bx=200+Math.sin(t*1.25)*90,by=hh-38-Math.abs(Math.sin(t*1.2))*Math.max(16,hh-144);c.shadowColor=p.modern?'#64f4d4':'transparent';c.shadowBlur=p.modern?17:0;c.fillStyle=p.modern?'#7beddb':'#c5d8d9';c.beginPath();c.roundRect(x-31,py,62,5,p.modern?3:0);c.fill();c.fillStyle='#efffff';c.beginPath();c.arc(bx,by,2.5,0,Math.PI*2);c.fill();c.restore();}if(!reduced)requestAnimationFrame(frame);}
requestAnimationFrame(frame);
